name: dt
description: |-
  [dt]
  Trivial tool for dart.
version: 2025.425.1054
homepage:
repository: "https://github.com/dart-pkg/dt"
environment:
  sdk: ^3.7.2
executables:
  dt: main
dependencies:
  args: ^2.7.0
  run: ^2025.424.1840
  sys: ^2025.425.243
dev_dependencies:
  lints: ^5.1.1
  output: ^1.0.7
  test: ^1.25.15
